name: 'Saplings - Base'
description: 'Simple base configuration for modern Drupal.'
type: 'Site'
recipes:
  - tour_core
install:
  # Core.
  - automated_cron
  - block_content
  - config
  - dynamic_page_cache
  - field_ui
  - menu_link_content
  - menu_ui
  - node
  - options
  - page_cache
  - path
  - path_alias
  - shortcut
  - taxonomy
  - views
  - views_ui
  # Contrib.
  - block_class
  - critical_css
  - diff
  - easy_breadcrumb
  - google_tag
  - menu_link_attributes
  - pathauto
  - redirect
  - redirect_404
  - simple_sitemap
  - sitemap
  - tour
  - ultimate_cron
  - views_custom_cache_tag
config:
  # Any configs that already exist will be skipped.
  strict: false
  import:
    # Core.
    block_content:
      # Lets bring in the view to list custom blocks.
      # But not the default custom block itself.
      - views.view.block_content
    shortcut: '*'
    taxonomy:
      # Not bringing in the Taxonomy view.
      - core.entity_view_mode.taxonomy_term.full
      - system.action.taxonomy_term_publish_action
      - system.action.taxonomy_term_unpublish_action
      - taxonomy.settings
    # Contrib.
    # Import diff entity view mode.
    diff: '*'
    # Import Pathauto actions.
    pathauto: '*'
    # Don't import optional Language config.
    redirect:
      - redirect.settings
      - system.action.redirect_delete_action
      - views.view.redirect
    # Import Redirect 404 view.
    redirect_404: '*'
    simple_sitemap: '*'
    # Import Sitemap tour.
    sitemap: '*'
  actions:
    # Sets Cron interval to 0.
    automated_cron.settings:
      simpleConfigUpdate:
        interval: 0
    # Users should not be able to set their own time zone.
    system.date:
      simpleConfigUpdate:
        timezone.default: America/New_York
        timezone.user.configurable: false
    # Turn on error reporting.
    system.logging:
      simpleConfigUpdate:
        error_level: some
    # Performance.
    system.performance:
      simpleConfigUpdate:
        cache.page.max_age: 900
        css.preprocess: true
        js.preprocess: true
    # Set home page.
    system.site:
      simpleConfigUpdate:
        page.front: /node/1
    # Only Admins can register accounts.
    user.settings:
      simpleConfigUpdate:
        cancel_method: user_cancel_block
        register: admin_only
        verify_mail: true
    # Easy Breadcrumbs.
    easy_breadcrumb.settings:
      simpleConfigUpdate:
        # Add Schema.org Breadcrumb markup.
        add_structured_data_json_ld: true
        # Remove breadcrumbs when only home appears.
        # Since we print the page title, this is only the home page.
        hide_single_home_item: true
    # Customize Menu item and link attributes.
    menu_link_attributes.config:
      simpleConfigUpdate:
        attributes.container_class:
          label: 'Menu item class'
          description: 'Add a CSS class to the menu item (li)'
        attributes.container_id:
          label: 'Menu item ID'
          description: 'Add a unique ID to the menu item.'
        attributes.class:
          label: 'Menu link class'
          description: 'Add a CSS class to the menu link (a)'
        attributes.id:
          label: 'Menu link ID'
          description: 'Add a unique ID to the menu link.'
        attributes.target:
          label: 'Menu link target'
          description: 'Set the link to open in the same window or a new one.'
    # Exclude 404s from the log.
    redirect_404.settings:
      simpleConfigUpdate:
        suppress_404: true
    # HTML Sitemap.
    sitemap.settings:
      simpleConfigUpdate:
        page_title: Sitemap
        plugins.frontpage:
          enabled: true
          weight: 0
          settings:
            title: ''
            rss: ''
          id: frontpage
          provider: sitemap
        plugins.menu:main:
          enabled: true
          weight: 0
          settings:
            title: ''
            show_disabled: false
          id: 'menu:main'
          provider: sitemap
        include_css: true
    # Set some broad permissions.
    user.role.authenticated:
      grantPermissions:
        - 'access content'
        - 'access shortcuts'
        - 'access user profiles'
        - 'view own unpublished content'
    user.role.anonymous:
      grantPermission: 'access content'
